package com.example.research_project.model;
/**
 * Keyword.java - Represents one keyword extracted from a paper.
 *
 * WHY IS THIS A SEPARATE CLASS?
 * A paper can have many keywords (one-to-many relationship).
 * We store each keyword as its own row in the 'keywords' table,
 * linked to a paper by paper_id (foreign key).
 *
 * Example:
 *   Paper id=5, title="Deep Learning..."
 *     -> Keyword id=1, paperId=5, keyword="deep learning"
 *     -> Keyword id=2, paperId=5, keyword="CNN"
 *     -> Keyword id=3, paperId=5, keyword="classification"
 */
public class Keyword {

    private int id;        // Auto-generated by SQLite
    private int paperId;   // Links this keyword to its Paper
    private String keyword; // The actual keyword text

    // ---- Constructors ----

    public Keyword() {}

    public Keyword(int paperId, String keyword) {
        this.paperId = paperId;
        this.keyword = keyword;
    }

    // ---- Getters and Setters ----

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getPaperId() { return paperId; }
    public void setPaperId(int paperId) { this.paperId = paperId; }

    public String getKeyword() { return keyword; }
    public void setKeyword(String keyword) { this.keyword = keyword; }

    @Override
    public String toString() {
        return "Keyword{id=" + id + ", paperId=" + paperId + ", keyword='" + keyword + "'}";
    }
}
