package com.example.research_project.model;


/**
 * Note.java - Represents a user note attached to a paper.
 *
 * Users can add their own notes to any paper.
 * Like keywords, each note is a separate row in the 'notes' table,
 * linked to a paper by paper_id.
 *
 * Example:
 *   Paper id=5, title="Deep Learning..."
 *     -> Note id=1, paperId=5, note="Read this before the exam", createdAt="2025-01-10"
 *     -> Note id=2, paperId=5, note="Compare with CNN paper",    createdAt="2025-01-12"
 */
public class Note {

    private int id;          // Auto-generated by SQLite
    private int paperId;     // Links this note to its Paper
    private String note;     // The note text written by the user
    private String createdAt; // When this note was created

    // ---- Constructors ----

    public Note() {}

    public Note(int paperId, String note, String createdAt) {
        this.paperId = paperId;
        this.note = note;
        this.createdAt = createdAt;
    }

    // ---- Getters and Setters ----

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public int getPaperId() { return paperId; }
    public void setPaperId(int paperId) { this.paperId = paperId; }

    public String getNote() { return note; }
    public void setNote(String note) { this.note = note; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    @Override
    public String toString() {
        return "Note{id=" + id + ", paperId=" + paperId + ", note='" + note + "'}";
    }
}