package com.example.research_project.model;

/**
 * Paper.java - The main data model of the application.
 *
 * WHAT IS A MODEL?
 * A model class simply holds data. It has no logic for saving to
 * the database or drawing on screen - it just stores information
 * about one research paper.
 *
 * WHY IS THIS SEPARATE?
 * Keeping data (model) separate from database logic (DAO) and
 * screen logic (controller) is a core OOP principle called
 * Separation of Concerns.
 *
 * ENCAPSULATION:
 * All fields are private. You access them through getters/setters.
 * This means no other class can accidentally corrupt the data
 * by directly changing a field.
 *
 * WHERE DOES IT FIT?
 *   main.fxml
 *      |
 *   MainController  <-- uses Paper objects to show data on screen
 *      |
 *   PaperService    <-- creates/validates Paper objects
 *      |
 *   PaperDAO        <-- saves/loads Paper objects from SQLite
 *      |
 *   Paper.java      <-- THIS FILE
 */
public class Paper {

    // --------------------------------------------------------
    // Fields (all private - OOP Encapsulation)
    // --------------------------------------------------------

    private int id;            // Auto-generated by SQLite (PRIMARY KEY)
    private String title;      // Title of the research paper (required)
    private String authors;    // Comma-separated author names
    private int year;          // Publication year (e.g. 2024)
    private String abstractText; // The abstract/summary of the paper
    private String methodology;  // Research methodology used
    private String findings;     // Key findings of the paper
    private String category;     // Topic category (e.g. "Machine Learning")
    private String source;       // Where the paper came from (URL, journal, etc.)
    private String filePath;     // Path to imported file, if any
    private String createdAt;    // Timestamp when this record was created
    private boolean favorite;    // Whether this paper is favorited (0 = no, 1 = yes)
    private String readingStatus = "UNREAD"; // "UNREAD", "READING", or "COMPLETED"

    // --------------------------------------------------------
    // Constructors
    // --------------------------------------------------------

    /**
     * Default constructor - creates an empty Paper.
     * Needed by FXMLLoader and some frameworks.
     */
    public Paper() {
    }

    /**
     * Constructor without favorite and readingStatus - for backwards compatibility.
     */
    public Paper(String title, String authors, int year, String abstractText,
                 String methodology, String findings, String category,
                 String source, String filePath, String createdAt) {
        this.title = title;
        this.authors = authors;
        this.year = year;
        this.abstractText = abstractText;
        this.methodology = methodology;
        this.findings = findings;
        this.category = category;
        this.source = source;
        this.filePath = filePath;
        this.createdAt = createdAt;
        this.favorite = false;
        this.readingStatus = "UNREAD";
    }

    /**
     * Full constructor - used when creating a Paper with all fields at once.
     */
    public Paper(String title, String authors, int year, String abstractText,
                 String methodology, String findings, String category,
                 String source, String filePath, String createdAt,
                 boolean favorite, String readingStatus) {
        this(title, authors, year, abstractText, methodology, findings, category, source, filePath, createdAt);
        this.favorite = favorite;
        this.readingStatus = (readingStatus == null || readingStatus.isBlank()) ? "UNREAD" : readingStatus;
    }

    // --------------------------------------------------------
    // Getters and Setters
    // --------------------------------------------------------

    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getAuthors() { return authors; }
    public void setAuthors(String authors) { this.authors = authors; }

    public int getYear() { return year; }
    public void setYear(int year) { this.year = year; }

    public String getAbstractText() { return abstractText; }
    public void setAbstractText(String abstractText) { this.abstractText = abstractText; }

    public String getMethodology() { return methodology; }
    public void setMethodology(String methodology) { this.methodology = methodology; }

    public String getFindings() { return findings; }
    public void setFindings(String findings) { this.findings = findings; }

    public String getCategory() { return category; }
    public void setCategory(String category) { this.category = category; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public String getFilePath() { return filePath; }
    public void setFilePath(String filePath) { this.filePath = filePath; }

    public String getCreatedAt() { return createdAt; }
    public void setCreatedAt(String createdAt) { this.createdAt = createdAt; }

    public boolean isFavorite() { return favorite; }
    public void setFavorite(boolean favorite) { this.favorite = favorite; }

    public String getReadingStatus() {
        return (readingStatus == null || readingStatus.isBlank()) ? "UNREAD" : readingStatus;
    }
    public void setReadingStatus(String readingStatus) {
        this.readingStatus = (readingStatus == null || readingStatus.isBlank()) ? "UNREAD" : readingStatus;
    }

    // --------------------------------------------------------
    // toString() - useful for debugging (prints a short summary)
    // --------------------------------------------------------

    @Override
    public String toString() {
        return "Paper{" +
                "id=" + id +
                ", title='" + title + "'" +
                ", authors='" + authors + "'" +
                ", year=" + year +
                ", category='" + category + "'" +
                "}";
    }
}